### ISSUE TITLE
IE11 crash in Demo

### ISSUE THREAD

**Issue by jorgjanke** [accorto/lightning-dart#36]
stack   "Error: Invalid argument.\n
   at InputElement.prototype.set$type (Function code:3761:59)
   at LInput.LInput$5$idPrefix$inGrid$withClearValue (http://lightningdart.com/indexPage.dart.js:32704:9)
   at Datepickers.get$content (http://lightningdart.com/indexPage.dart.js:36716:9)
   at DemoFeature.DemoFeature$8$devStatus$hints$issues$plans$sldsPath$sldsStatus (http://lightningdart.com/indexPage.dart.js:36963:9)
   at Datepickers.static.Datepickers$ (http://lightningdart.com/indexPage.dart.js:36762:11)
   at Anonymous function (http://lightningdart.com/indexPage.dart.js:19900:9)
   at _RootZone.runUnary$2 (http://lightningdart.com/indexPage.dart.js:8864:11)
   at _Future__propagateToListeners_handleValueCallback.call$0 (http://lightningdart.com/indexPage.dart.js:7450:11)
   at _Future.static._Future__propagateToListeners (http://lightningdart.com/indexPage.dart.js:7357:19)
   at _Future._completeWithValue$1 (http://lightningdart.com/indexPage.dart.js:7236:9)"

**Comment by jorgjanke** [comment]
```
  get$source: function(_) {
    return "    LForm form = new LForm.stacked(\"datePick\");\n\n    LDatepicker dp = new LDatepicker(\"date\")\n      ..label = \"Date Picker\";\n    if (optionWeekSelect)\n      dp.mode = LDatepicker.MODE_WEEK_FIRST;\n    dp.value = null;\n    form.addEditor(dp);\n\n    LInputDate id1 = new LInputDate(\"id1\")\n      ..label = \"Date Input Html5 (falls back if not supported)\";\n    id1.value = null;\n    form.addEditor(id1);\n\n    LInputDate id2 = new LInputDate(\"id2\")\n      ..label = \"Date Input\"\n      ..html5 = false;\n    id2.value = null;\n    form.addEditor(id2);\n    ";
  },
  optionWeekCb$0: function() {
    var cb = F.LCheckbox$("optionW", this.id, false);
    cb.set$label(0, "Option: Week Select (first day)");
    J.get$onClick$x(cb.input).listen$1(new F.Datepickers_optionWeekCb_closure(this, cb));
    return cb;
  },
  get$options: function(_) {
    var list = H.setRuntimeTypeInfo([], [L.EditorI]);
    list.push(this.optionWeekCb$0());
    return list;
  },
  static: {Datepickers$: function() {
      var t1, t2, t3, t4;
      t1 = ["date constants (e.g. month names) are translated"];
      t2 = ["css: week select with crossing month boundary"];
      t3 = ["date ranges"];
      t4 = new F.Datepickers(false, C.HtmlDocument_methods.createElement$1(document, "div"), "datepickers", "Datepickers", t1, null, "prototype", "partial", t2, t3, null, null, null, null, null);
      t4.DemoFeature$8$devStatus$hints$issues$plans$sldsPath$sldsStatus("datepickers", "Datepickers", "partial", t1, t2, t3, null, "prototype");
      return t4;
    }}
},
```

crash at:
t4.DemoFeature$8$devStatus$hints$issues$plans$sldsPath$sldsStatus("datepickers", "Datepickers", "partial", t1, t2, t3, null, "prototype");

  wrapper = C.HtmlDocument_methods.createElement$1(document, "div");
        t3 = J.getInterceptor$x(wrapper);
        t3.get$classes(wrapper).add$1(0, "slds-m-left--small");
        t3.append$1(wrapper, tab.element);
        t2.append$1(t1, wrapper);
        if (this.get$content(this) != null) { <--- 36962
          sc = tab.addTab$2$name("Small", "s");

-- 36715
        id1 = new F.LInputDate(t3, null, "??", "date", t4, false, t5, t6, null, null, t7, null, null, null, false, null, null, null, null, L.Settings_getAsBool("nativeHtml5", false), null, null, null, null, null, null, null, null);
        id1.LInput$5$idPrefix$inGrid$withClearValue("id1", "date", null, false, false);

**Comment by jorgjanke** [comment]
input type="date" crashed the site
